   name: python-safety-check 				# the name of this work flow
   on: [push]  
   # Specify the event that automatically triggers the workflow file. This example uses the push event, so that the jobs run every time someone pushes a change to the repository

   jobs:  								# gather all the jobs that run in the workflow
     python-job:
       runs-on: ubuntu-latest   		# Set the type of machine to run on
       steps:
         - uses: aufdenpunkt/python-safety-check@master   # Step 1: Checks out a copy of your repository on the ubuntu-latest machine

         - name: python-check       # Step 2: Type the word 'Hello World'
           run: aufdenpunkt/python-safety-check	
