name: Python-check

on:
  push:
    branches:
      - main

env:
  DEP_PATH: /path/to/ChatBot/requirements.txt

jobs:
  safety-check:
    runs-on: ubuntu-latest
    steps:
         - name: python-check       
         - uses: aufdenpunkt/python-safety-check@master
