name: python check
on:
  push:
    branches:
      - main
env:
 DEP_PATH: requirements.txt
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: python check
        uses: aufdenpunkt/python-safety-check@master
